VERSION = "0.62"
YOUTUBE_ICON = "https://yt3.ggpht.com/a/AATXAJxHHP_h8bUovc1qC4c07sVXxVbp3gwDEg-iq8gbFQ=s100-c-k-c0xffffffff-no-rj-mo"
USAGE_TEXT = "Send a search phrase or a link to play a song!"
CONFIG_PATH = "config.ini"
SPONSORBLOCK_MUSIC_API = "https://sponsor.ajay.app/api/skipSegments?videoID={0}&category=music_offtopic"
INVITE_LINK_FORMAT = "https://discord.com/api/oauth2/authorize?client_id={0}&permissions=8&scope=bot%20applications.commands"
